# .pre-commit-config.yaml
repos:
  # General file fixes
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: debug-statements  # Finds forgotten print() statements
      - id: mixed-line-ending
        args: ['--fix=lf']

  # isort
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: Sort imports with isort

  # Black
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        name: Format with Black

  # Autoflake
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
        args: [
          --remove-all-unused-imports,
          --remove-unused-variables,
          --remove-duplicate-keys,
        ]

  # Flake8 (basic linting)
  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args: [
          '--max-line-length=100',
          '--ignore=E203,E501,W503',
          '--exclude=.git,__pycache__,old,build,dist,venv,.venv'
        ]
