[tool.black]
line-length = 100  # Gives you more room for complex DFS logic
target-version = ['py311', 'py312', 'py313']  # You're using Python 3.13.3
include = '\.pyi?$'
extend-exclude = '''
(
  /(
      \.git
    | \.venv
    | venv
    | build
    | dist
    | __pycache__
    | .*\.backup
    | backup_.*
    | data/cache
    | output
    | exports
    | archives
  )/
)
'''

# Optional: String formatting preferences
# skip-string-normalization = true  # Uncomment to keep single quotes

[tool.isort]
profile = "black"  # Makes isort compatible with black
line_length = 100

[tool.autoflake]
remove-all-unused-imports = true
remove-unused-variables = true
remove-duplicate-keys = true
